# Generated by Django 5.2 on 2025-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='recusaro',
            field=models.BooleanField(default=False),
        ),
    ]
