# Generated by Django 5.2 on 2025-04-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_post_aprovado_post_recusaro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recusaro',
            new_name='recusado',
        ),
    ]
