# Generated by Django 5.2 on 2025-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_post_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do vídeo do YouTube'),
        ),
    ]
